#ifndef RESEARCH_SSH_CORE_H
#define RESEARCH_SSH_CORE_H

#pragma once

/* AUTO-GENERATED by cbindgen via build.rs. DO NOT EDIT BY HAND. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

// Stable error codes returned across the C ABI.
//
// `0` always means success. The numeric values are part of the ABI contract and
// must never be reordered or reused. A human-readable, UTF-8 description for any
// code is available via [`ffi::rscore_error_message`].
typedef enum {
    // Operation succeeded.
    RsErrorCode_Ok = 0,
    // A required pointer argument was null.
    RsErrorCode_NullArgument = 1,
    // A C string argument was not valid UTF-8.
    RsErrorCode_InvalidUtf8 = 2,
    // The operation is not valid in the current session state.
    RsErrorCode_InvalidState = 3,
    // The requested provider or session capability is not available.
    RsErrorCode_ProviderUnavailable = 4,
    // Establishing the connection failed.
    RsErrorCode_ConnectFailed = 5,
    // The session is not connected.
    RsErrorCode_NotConnected = 6,
    // The operation was cancelled.
    RsErrorCode_Cancelled = 7,
    // The async runtime reported a failure (e.g. the worker is gone).
    RsErrorCode_RuntimeError = 8,
    // A panic was caught at the FFI boundary (should never reach the caller as UB).
    RsErrorCode_Panic = 9,
    // An unexpected internal error occurred.
    RsErrorCode_Internal = 10,
} RsErrorCode;

// Discriminator for [`RsEvent`].
typedef enum {
    // `state` is meaningful; the session changed lifecycle state.
    RsEventKind_StateChanged = 0,
    // `data`/`data_len` carry terminal bytes (already batched).
    RsEventKind_Data = 1,
    // `error_code`/`message` describe an error.
    RsEventKind_Error = 2,
    // The server presented an unrecognised host key; `message` carries its
    // fingerprint. The UI must confirm via `rscore_session_confirm_host_key`.
    RsEventKind_HostKeyPrompt = 3,
} RsEventKind;

// Kind of a remote directory entry.
typedef enum {
    // Regular file.
    RsFileKind_File = 0,
    // Directory.
    RsFileKind_Directory = 1,
    // Symbolic link.
    RsFileKind_Symlink = 2,
    // Anything else.
    RsFileKind_Other = 3,
} RsFileKind;

// Discriminator for [`RsFsResult`].
typedef enum {
    // `entries`/`entry_count` are valid (directory listing or single stat).
    RsFsResultKind_Listing = 0,
    // `data`/`data_len` are valid (file contents).
    RsFsResultKind_Content = 1,
    // A mutating op succeeded; no payload.
    RsFsResultKind_Ok = 2,
    // `error_code`/`message` are valid.
    RsFsResultKind_Error = 3,
} RsFsResultKind;

// Which provider backs a session. Numeric values are part of the C ABI.
typedef enum {
    // In-process simulator used for framework/UI development and tests.
    RsProviderKind_Mock = 0,
    // Real SSH via the `russh` crate; requires the `russh` feature.
    RsProviderKind_Russh = 1,
} RsProviderKind;

// Lifecycle state of a session. The numeric values are part of the ABI.
typedef enum {
    // Created but no connection attempt has started.
    RsSessionState_Idle = 0,
    // A connection attempt is in progress.
    RsSessionState_Connecting = 1,
    // Connected and ready to exchange data.
    RsSessionState_Connected = 2,
    // A disconnect was requested and is in progress.
    RsSessionState_Disconnecting = 3,
    // Cleanly disconnected.
    RsSessionState_Disconnected = 4,
    // Terminated due to an error.
    RsSessionState_Failed = 5,
} RsSessionState;

// Opaque handle to the core (owns the async runtime).
typedef struct RsCore RsCore;

// Opaque handle to a single session.
typedef struct RsSession RsSession;

// Parameters for creating a session. Strings are borrowed, NUL-terminated UTF-8;
// they are copied during the call and need not outlive it.
typedef struct {
    // Hostname or IP (UTF-8, NUL-terminated).
    const char *host;
    // TCP port.
    uint16_t port;
    // Login user name (UTF-8, NUL-terminated).
    const char *username;
    // Which provider to use.
    RsProviderKind provider;
} RsSessionConfig;

// C-ABI view of a single event.
//
// # Pointer ownership (ABI contract)
// `data` and `message` point into buffers owned by the Rust core. They are valid
// **only for the duration of the [`RsEventCallback`](crate::ffi::RsEventCallback)
// invocation** that delivered them. The C++ side MUST copy anything it needs
// before returning from the callback. Rust frees the backing buffers immediately
// after the callback returns.
typedef struct {
    // Which union-ish fields are valid.
    RsEventKind kind;
    // Valid when `kind == StateChanged`.
    RsSessionState state;
    // Valid when `kind == Error`.
    RsErrorCode error_code;
    // Terminal bytes; valid when `kind == Data`. May be null otherwise.
    const uint8_t *data;
    // Length of `data` in bytes.
    uintptr_t data_len;
    // UTF-8, null-terminated message; valid when `kind == Error`. May be null.
    const char *message;
} RsEvent;

// C-ABI view of one directory entry. Pointers valid only during the callback.
typedef struct {
    // Base name (UTF-8).
    const char *name;
    // Full remote path (UTF-8).
    const char *path;
    // Entry kind.
    RsFileKind kind;
    // Size in bytes.
    uint64_t size;
    // Last-modified time (Unix seconds), -1 if unknown.
    int64_t modified_unix;
    // POSIX permission bits.
    uint32_t mode;
    // Whether the in-app editor should offer to open this as text.
    bool editable_text;
} RsFileEntry;

// Result of a file operation, correlated by `request_id`.
typedef struct {
    // Matches the id returned by the `rscore_session_fs_*` call.
    uint64_t request_id;
    // Which fields are valid.
    RsFsResultKind kind;
    // Listing entries (valid when `kind == Listing`).
    const RsFileEntry *entries;
    // Number of entries.
    uintptr_t entry_count;
    // File bytes (valid when `kind == Content`).
    const uint8_t *data;
    // Length of `data`.
    uintptr_t data_len;
    // Error code (valid when `kind == Error`).
    RsErrorCode error_code;
    // UTF-8 error message (valid when `kind == Error`).
    const char *message;
} RsFsResult;

// Event callback. Receives a batch of `count` events. See the module-level
// ownership contract for pointer lifetimes and threading rules.
typedef void (*RsEventCallback)(void *user_data, const RsEvent *events, uintptr_t count);

// File-result callback: receives a batch of `count` results.
typedef void (*RsFileCallback)(void *user_data, const RsFsResult *results, uintptr_t count);

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Returns the core version as a static, NUL-terminated UTF-8 string. The pointer
// is valid for the lifetime of the process and must NOT be freed.
const char *rscore_version(void);

// Returns a static, NUL-terminated UTF-8 description of an error code. Must NOT
// be freed.
const char *rscore_error_message(RsErrorCode code);

// Frees a heap string previously returned by an API that transfers ownership.
// Safe to call with null. (Reserved: current APIs return only static strings.)
void rscore_string_free(char *s);

// Creates the core (and its async runtime). On failure returns null and writes a
// code to `out_err` (if non-null). Destroy with [`rscore_destroy`].
RsCore *rscore_create(RsErrorCode *out_err);

// Destroys a core created by [`rscore_create`]. Safe to call with null. All
// sessions created from this core must be destroyed first.
void rscore_destroy(RsCore *core);

// Creates a session on `core`. Returns null on failure and writes a code to
// `out_err`. The `cb`/`user_data` pair receives batched events. Destroy with
// [`rscore_session_destroy`].
RsSession *rscore_session_create(RsCore *core,
                                 const RsSessionConfig *config,
                                 void (*cb)(void *user_data, const RsEvent *events, uintptr_t count),
                                 void *user_data,
                                 RsErrorCode *out_err);

// Destroys a session. Blocks briefly to join the driver task so no further
// callbacks can fire after this returns. Safe to call with null.
void rscore_session_destroy(RsSession *session);

// Requests a connection. Returns [`RsErrorCode::Ok`] if the request was queued.
RsErrorCode rscore_session_connect(RsSession *session);

// Requests a disconnect.
RsErrorCode rscore_session_disconnect(RsSession *session);

// Sends `len` bytes (a command line / keystrokes) to the remote.
RsErrorCode rscore_session_send(RsSession *session, const uint8_t *data, uintptr_t len);

// Cancels the in-flight operation (if any). Always succeeds for a live handle.
RsErrorCode rscore_session_cancel(RsSession *session);

// Delivers the user's decision for a pending host-key prompt (the
// `RsEventKind_HostKeyPrompt` event). `accept = true` trusts the key and lets the
// connection proceed; `false` rejects it and aborts the connection. No-op if no
// prompt is pending.
RsErrorCode rscore_session_confirm_host_key(RsSession *session, bool accept);

// Hands a sensitive credential (e.g. password bytes) to the session's provider.
// The bytes are copied into a zeroizing buffer immediately. Reserved for real
// providers; the mock discards it.
RsErrorCode rscore_session_set_password(RsSession *session, const uint8_t *data, uintptr_t len);

// Registers the file-result callback for a session. Required before any
// `rscore_session_fs_*` call delivers results.
RsErrorCode rscore_session_set_file_callback(RsSession *session,
                                             void (*cb)(void *user_data,
                                                        const RsFsResult *results,
                                                        uintptr_t count),
                                             void *user_data);

// Lists a directory (empty `path` = the connection's home dir). Returns a request id.
uint64_t rscore_session_fs_list(RsSession *session, const char *path);

// Stats a single path (result delivered as a one-element listing).
uint64_t rscore_session_fs_stat(RsSession *session, const char *path);

// Reads up to `max_len` bytes of a file. Returns a request id.
uint64_t rscore_session_fs_read(RsSession *session, const char *path, uint64_t max_len);

// Overwrites a file with `len` bytes (editor save / upload). Returns a request id.
uint64_t rscore_session_fs_write(RsSession *session,
                                 const char *path,
                                 const uint8_t *data,
                                 uintptr_t len);

// Renames / moves `from` to `to`. Returns a request id.
uint64_t rscore_session_fs_rename(RsSession *session, const char *from, const char *to);

// Removes a path (recursively for directories when `recursive`). Returns a request id.
uint64_t rscore_session_fs_remove(RsSession *session, const char *path, bool recursive);

// Creates a directory. Returns a request id.
uint64_t rscore_session_fs_mkdir(RsSession *session, const char *path);

// Copies `from` to `to`. Returns a request id.
uint64_t rscore_session_fs_copy(RsSession *session, const char *from, const char *to);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* RESEARCH_SSH_CORE_H */
